version: 2.1

commands:
  print:
    parameters:
      message:
        type: string
    steps:
      - run: echo << parameters.message >>

jobs:
  daily-message:
    machine: true
    parameters:
      message:
        type: string
    steps:
      - print:
          message: Printing << parameters.message >>

  build:
    machine:
      image: ubuntu-2004:2023.04.2
    environment:
      GIT_URL: << pipeline.project.git_url >>
    steps:
      - run: |
          echo $TESTING_VALUE
          echo $GIT_URL