version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  lint:
    executor:
      name: android/android-docker
      tag: "2022.09"
    steps:
      - checkout
      - run:
          name: "Running our linter"
          command: ./gradlew detekt

  unit-test:
    executor:
      name: android/android-docker
      tag: "2022.09"
    steps:
      - checkout
      - run:
          name: "Running our unit test"
          command: ./gradlew test

  release-build:
    executor:
      name: android/android-machine
      tag: "2023.06.1"
    filters:
      tags:
        only: /^\[ci\]/
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release

workflows:
  build:
    jobs:
      - lint
      - unit-test
      - release-build:
          requires:
            - lint
            - unit-test
