version: 2.1

jobs:
  lint:
    executor:
      name: android/android-docker
    steps:
      - checkout
      - run:
          name: "Running our linter"
          command: ./gradlew detekt

workflows:
  say-hello-workflow:
    jobs:
      - lint
