version: 2.1
orbs:
  android: circleci/android@2.1.2

jobs:
  build:
    machine:
      image: ubuntu-2004:2023.04.2
    steps:
      - run: echo $TESTING_VALUE
      - run: echo ${GOOGLE_SERVICES_ACCOUNT}
