version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:2023.04.2
    environment:
      GIT_URL: << pipeline.project.git_url >>
    steps:
      - run: |
          echo $TESTING_VALUE
          echo $GIT_URL
          echo $CIRCLE_COMMIT_MESSAGE
          echo $CIRCLE_SHA1
      - run:
          name: Print Commit Message
          command: echo $(git log --format=%B -n 1 $CIRCLE_SHA1)