version: 2.1

jobs:
  lint:
    executor:
      name: android/android-docker
      tag: 2022.08.1
    steps:
      - checkout
      - run:
          name: "Running our linter"
          command: ./gradlew detekt

workflows:
  build:
    jobs:
      - lint
